# Generated by Django 2.0.5 on 2018-05-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrelation',
            name='member_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberrelation_member_relations_rel', to='osm.OSM_Relation'),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='member_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Way'),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='sequence',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='type',
            field=models.CharField(blank=True, choices=[('n', 'node'), ('w', 'way'), ('r', 'relation')], max_length=1),
        ),
    ]
