# Generated by Django 2.0.5 on 2018-05-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0002_auto_20180516_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrelation',
            name='member_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.Node'),
        ),
    ]
