# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 17:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osm', '0003_auto_20180516_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
